- menu_name: "바로가기"

- name: "문의"
  url: "/contact/"
  title: "문의"

- name: "RSS"
  url: "/feed.xml"
  title: "RSS 피드 구독"

- name: "Atom"
  url: "/atom.xml"
  title: "Atom 피드 구독"

- name: "sitemap.xml"
  url: "/sitemap.xml"
  title: "구글 웹마스터용 사이트맵"
