backend:
  name: github
  repo: soleprizestudio/soleprizestudio.github.io
  branch: main
  base_url: 'https://home-page-cms.soleprizestudio.workers.dev'

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'post'
    label: '게시물'
    label_singular: '게시물'
    folder: 'src/data/post'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: '제목', name: 'title', widget: 'string' }
      - { label: '요약', name: 'excerpt', widget: 'string', required: false }
      - { label: '카테고리', name: 'category', widget: 'string', required: false }
      - {
          label: '태그',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: false,
          required: false,
          field: { label: '태그', name: 'tag', widget: 'string' },
        }
      - { label: '대표 이미지', name: 'image', widget: 'image', required: false }
      - { label: '발행일', name: 'publishDate', widget: 'datetime', required: false }
      - { label: '작성자', name: 'author', widget: 'string', required: false, default: '평발' }
      - { label: '임시글(draft)', name: 'draft', widget: 'boolean', required: false, default: true }
      - { label: '본문', name: 'body', widget: 'markdown' }
